### ISSUE TITLE
Sending an attachment with a message

### ISSUE THREAD

**Issue by rorourke-iot** [marchfederico/node-sparkclient#2]
Goal: Send an attachment via a relative path

I have successfully attached a file to a create message request using the documented mechanism (http://site/file). I'm looking to do this with a relate file path (or even absolute within the site structure). Attempting to do so always results in an error (Unable to retrieve content.). Placing code to read the file just prior to sending the message successfully returns the contents of the file. I've tried with both "file" and "files" in an attempt to get this to work. I've also tried true relative and absolute paths using the file system structure.

Thoughts?

    var readmePath = path.join(__dirname, 'README.md');
    fs.readFile(readmePath, function(err, data) {
        if (err)
            console.log(err);
        console.log(data);
    });
    console.log(readmePath);
    var messageParams = {};
    messageParams.file = readmePath;
    messageParams.markdown = true;

    spark.createMessage(command.message.roomId, "Here is the document you requested.", messageParams, function(err, message) {
        if (err) {
            console.log("WARNING: could not post attachment to room: " + command.message.roomId);
            console.log(err);
            return;
        }
    });

**Comment by geekbleek** [comment]
This should be resolved with the latest commit. Previously, only file URL's were allowed and Spark would go pull the file directly from that URL.  Now you can pass a file buffer in such as 👍 

   ```
 //You can also directly upload a file by passing in a file buffer, in which case the returned Spark response will include the file ID. When directly uploading a file you must specify a filename as this buffer

var data = fs.readFileSync('document.xlsx');
messageParams = {}  // Message Parameters are optional
messageParams.file = data
messageParams.filename = 'My uploaded file.xlsx'

    // for a direct 1:1 message just use the users email address as the first parameter or person id
    sparkClient.createMessage('marfeder@cisco.com', 'Here is the uploaded file!', messageParams, function(err, response) {
        if (!err)
            console.dir(response.id)
    })
```

Let us know if that doesn't solve it!
